### ISSUE TITLE
Sign Up yapılırken hangi bilgiler alınmalı. 

### ISSUE THREAD

**Issue by mctozal** [mctozal/SmartAmbulance#8]
Bilgiler word dosyasına kaydedilip eklenmeli

**Comment by Hidalgo71** [comment]
**SING UP**

- Driver Name
- Driver Surname
- TCno(for driverID)
- Mail(optional)

> After driver sign up, he/she can add an ambulance.

- Ambulance Plate
- Vehicle Licence
- Vehicle Licence Date (for follow vehicle inspection, age > 5 year, car goes to check every 2 year)
- Ambulance Type (Patient Transfer, Emergency, intencive care)
